var GAME_LEVELS = [
   ["                                                                                 ",
   "                                                                                  ",
   "                                                                                  ",
   "                                                                                  ",
   "                                       o                                          ",
   "                                       x                                          ",
   "                                    xxx                   o       o               ",
   "                                 x                  xx  x!x   x  !x!x             ",
   "                                  x         xxxxx                    x      	  ",
   "                   o                x                           	      x       ",
   "                  xxxxxxxx          xxxx                               x          ",
   "                 x                         xx                           x      xx ",
   "  xx            x                               x                              x  ",
   "  x            x                                                               x  ",
   "  x           x                           xxxxx                                x  ",
   "  x          xxxx                      xx                                    o x  ",
   "  x  @       x  x              xx                                  xxxxx     * x  ",
   "  xxxxxxxxxxxx  xxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxx!!!!!!!     		 xxxxxxxxxxxx ",
   "                            x!!!!!!!x            x!!!!!!!!!!!!!!!!!!!!            ",
   "                            x!!!!!!!x            x!!!!!!!!!!!!!!!!!!!!            ",
   "                            x!!!!!!!x            x!!!!!!!!!!!!!!!!!!!!            ",
   "                            xxxxxxxxx            xxxxxxxxxxxxxxxxxxxxx            ",
   "                                                                                  ",
   "                                                                                  "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                       xxx                                                                    ",
   "                                       x x                 !!!        !!!  xxx                                ",
   "                                       x x                 !x!        !x!                                     ",
   "                                     xxx xxx                x          x                                      ",
   "                                      x   x                 x          x       xxx                            ",
   "                                      x   x                 x          x      x!!!x                           ",
   "                                      x   x                 xxxxxxxxxxxx       xxx                            ",
   "                                     xx   xx      x   x      x                                                ",
   "                                      x   x                                                                   ",
   "                                      x   x           x                                                       ",
   "                                      x   x           x                                                       ",
   "                                     xx   xx          x                                                       ",
   "                                      x       x                                                               ",
   "                                                  x                                                           ",
   "                                                                                                              ",
   "                                                    x                                                         ",
   "                                                      x                                                       ",
   "                                                      x              x                                        ",
   "                             xxxxxxxxxxxxxxx          x!!!!!!!!!!!!!!x                                        ",
   "                             xxxxxxxxxxxxxxx          x!!!!!!!!!!!!!!x                                        ",
   "                             x             xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        ",
   "                             x                                                                       x        ",
   "  xxx                        x                                         x                             x        ",
   "  x x                        x                                         x                             x        ",
   "  x                          x   o         x                           x                             x        ",
   "  x                          x   x       x x                           x                             x        ",
   "  x                          x         x   x                     o o   x                             x        ",
   "  x                           x       x    x          xx|  |x| |xxxx|           xx                   x   	  ",
   "  x            o      o      ox            x        x                       xxx  |          xx       x        ",
   "  x @    xxxvxxxvxxxvxxxvxxxxxvv   x       x                   x            v  v            x        x        ",
   "  x     x                            xx    x      x              x x                   |    ||       x        ",
   "  x     $                	               x x	 					                                 x        ",
   "  x        *                               x   xxxxxx    xx   xx                                 *   x        ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     ",
   "                                                                                                              ",
   "                                         x                                                                    "],
  ["                                         x                                                                    ",
   "                                         x                                                                    ",
   " @                                       x                                                                    ",
   " o   o   o   o   o  o    o  o  o  o      x                                                                    ",
   " +   +   +   +   +  +    +  +  +  +      x                                                                    ",
   "                                         x                                                                    ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x   x                                                                    ",
   "                 |       v     |   |   |   xvxx                                                               ",
   "               |                          	    v                                                             ",
   "             |                                  x                                                             ",
   "                                                x                                                             ",
   "        |                     +   +   +        $x                                                             ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                         ",
   "      =              o          o       o    =      x                                                         ",
   "                                                    x                                                         ",
   "         x    x++++++++o+++++++++++o+++++++o++xxxx  x                                                         ",
   "            x          +     |   = +  |    +    |   x                                                         ",
   "     =     x             =      |         |         x                                                         ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x                                   xx   xx      x   x    ",
   "                                          xxxxxx  xxxxx              x x                                      ",
   "                                          x           x                    x!!!x                              ",
   "                                          x           x                     xxx                               ",
   "                                          x      x    x                                                       ",
   "                                          x=     =    x            xxx                                        ",
   "                                          x         x x           x!!!x                                       ",
   "                                          x          =x     o      xxx       xxx                              ",
   "                                          xx          x                     x!!!x                             ",
   "                              o   o       x      x    x     x                xxv        xxx                   ",
   "                                          x   !!!!!!!!x              x                 x!!!x                  ",
   "                             xxx xxx xxx xx   x   o o  x!!!!!!!!!!!!!!x                   vx                  ",
   "                             x                x!!!!!!!!!!!!x                                                  ",
   "                             x               xxxxxxxxxxxxxxxxxxxxxxxxxx     x                                 ",
   "                             xx            xxx                              x                                 ",
   "  x                          x             x                                x                                 ",
   "  x      =             =     x      o o    x                                x                                 ",
   "  x               =   =       x    xxxx  ++x                                x                                 ",
   "  x                  =     =   x           x                                x                                 ",
   "  x   =          =             x                                            x                                 ",
   "  x                    = =     x                   |xxxx|    |xxxx|         x                                 ",
   "  x        =             =     x                                            x                                 ",
   "  x                =           x       xxxxx       |    |    |    |         x                                 ",
   "  x                =           x  o    x!!!!                                x                                 ",
   "  x       =                    xxxxxxxxxxxxx                              o x                                 ",
   "  x                           x           x!      =             =         % x                                 ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
 
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
